# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time',
            new_name='cooking_time_hours',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
