# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20170302_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
